"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api, resolveUserId } from "@/lib/api-client";
import { getLocalProgressHistory } from "@/lib/local-store";
import { CONDITIONS } from "@/lib/constants";

export default function ReportPage() {
  const router = useRouter();
  const [summary, setSummary] = useState<Record<string, unknown> | null>(null);
  const [mealPlan, setMealPlan] = useState<Record<string, unknown> | null>(null);
  const [macros, setMacros] = useState<Record<string, unknown> | null>(null);
  const [loading, setLoading] = useState(true);
  const [email, setEmail] = useState("");
  const [emailSent, setEmailSent] = useState(false);

  useEffect(() => {
    const id = resolveUserId();
    if (!id) { router.push("/onboarding/profile"); return; }
    Promise.all([
      api.getUserSummary(id),
      api.getMealPlan(id),
      api.getMacros(id),
    ]).then(([s, m, mx]) => {
      setSummary(s as Record<string, unknown>);
      setMealPlan(m as Record<string, unknown>);
      setMacros(mx as Record<string, unknown>);
      setLoading(false);
    });
  }, [router]);

  const progressHistory = getLocalProgressHistory(30);
  const recentLogs = progressHistory.logs.slice(0, 7);

  const conditions = (summary?.condition_codes as string[]) || [];
  const conditionLabels = conditions.map((code) => {
    const c = CONDITIONS.find((x) => x.code === code);
    return c ? `${c.icon} ${c.label}` : code;
  });

  const buildReportText = () => {
    const date = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
    const name = String(summary?.name || "User");
    const goal = String(summary?.primary_goal || "—").replace(/_/g, " ");
    const cal = Math.round((macros as Record<string, number>)?.calories || 0);
    const protein = Math.round((macros as Record<string, number>)?.protein_g || 0);
    const carbs = Math.round((macros as Record<string, number>)?.carbs_g || 0);
    const fat = Math.round((macros as Record<string, number>)?.fat_g || 0);

    const meals = (mealPlan?.meals as unknown[]) || [];
    const mealLines = meals.map((m: unknown) => {
      const slot = (m as Record<string, unknown>);
      const items = ((slot.items as unknown[]) || []).map((i: unknown) => ((i as Record<string, unknown>)?.food as Record<string, unknown>)?.name as string || "").filter(Boolean);
      return `  ${String(slot.slot).replace(/_/g, " ").toUpperCase()}: ${items.join(", ")}`;
    }).join("\n");

    const progressLines = recentLogs.length > 0
      ? recentLogs.map((l) => `  ${l.log_date}: Weight ${l.weight_kg || "—"}kg | BP ${l.bp_systolic ? `${l.bp_systolic}/${l.bp_diastolic}` : "—"} | Sugar F:${l.blood_sugar_fasting || "—"} PM:${l.blood_sugar_post_meal || "—"} | Sleep ${l.sleep_hours || "—"}h | Steps ${l.steps_count?.toLocaleString() || "—"}`).join("\n")
      : "  No progress data logged yet.";

    return `healthCopilot — Personal Health Report
Generated: ${date}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PROFILE
Name: ${name}
Health Goal: ${goal}
Conditions: ${conditionLabels.length > 0 ? conditionLabels.join(", ") : "None selected"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DAILY NUTRITION TARGETS
Calories:  ${cal} kcal
Protein:   ${protein}g
Carbs:     ${carbs}g
Fat:       ${fat}g

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TODAY'S MEAL PLAN
${mealLines}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

RECENT PROGRESS (last 7 days)
${progressLines}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DAILY WELLNESS REMINDERS
• Walk 30 min daily — reduces heart disease risk by 35%
• Strength train 2-3x/week — lowers blood sugar and builds metabolism
• Eat protein at every meal — keeps you full and supports muscle
• 7-8 hours sleep — regulates hunger hormones and insulin
• 10 min meditation daily — lowers cortisol and blood pressure
• Drink water before meals — reduces hunger naturally
• Half your plate = vegetables at every meal

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚕ This report is for personal wellness tracking only. It is not a substitute for medical advice. Always consult your doctor before making changes to diet, exercise or medications.

Generated by healthCopilot — amit33-design.vercel.app`;
  };

  const handleEmailReport = () => {
    const subject = encodeURIComponent("My healthCopilot Health Report");
    const body = encodeURIComponent(buildReportText());
    const to = encodeURIComponent(email || "");
    window.open(`mailto:${to}?subject=${subject}&body=${body}`, "_self");
    setEmailSent(true);
    setTimeout(() => setEmailSent(false), 4000);
  };

  const handlePrint = () => window.print();

  if (loading) {
    return (
      <div className="p-6 md:p-8 max-w-4xl mx-auto space-y-4">
        {[1,2,3,4].map((i) => <div key={i} className="h-32 shimmer rounded-2xl" />)}
      </div>
    );
  }

  const cal = Math.round((macros as Record<string, number>)?.calories || 0);
  const protein = Math.round((macros as Record<string, number>)?.protein_g || 0);
  const carbs = Math.round((macros as Record<string, number>)?.carbs_g || 0);
  const fat = Math.round((macros as Record<string, number>)?.fat_g || 0);
  const meals = (mealPlan?.meals as unknown[]) || [];

  return (
    <div className="p-6 md:p-8 max-w-4xl mx-auto space-y-6 animate-fade-in">

      {/* Header */}
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-black text-gray-900">My Health Report</h1>
          <p className="text-gray-400 text-sm mt-1">
            {new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}
          </p>
        </div>
        <div className="flex gap-2 flex-wrap no-print">
          <button
            onClick={handlePrint}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-gray-200 text-gray-700 text-sm font-semibold hover:bg-gray-50"
          >
            🖨 Print / Save PDF
          </button>
        </div>
      </div>

      {/* Email section */}
      <div className="no-print bg-gradient-to-r from-violet-50 to-sky-50 border border-violet-200 rounded-2xl p-5">
        <div className="font-bold text-gray-900 mb-1">📧 Email this report to yourself</div>
        <p className="text-sm text-gray-500 mb-3">
          Enters your email, click Send — your email app will open with the full report pre-filled.
        </p>
        <div className="flex gap-3 flex-wrap">
          <input
            type="email"
            placeholder="your@email.com"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="flex-1 min-w-0 px-4 py-2.5 rounded-xl border border-gray-200 focus:border-violet-400 focus:ring-2 focus:ring-violet-100 outline-none text-sm"
          />
          <button
            onClick={handleEmailReport}
            disabled={!email}
            className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-violet-500 to-sky-500 text-white font-bold text-sm hover:opacity-90 disabled:opacity-40 disabled:cursor-not-allowed"
          >
            {emailSent ? "✓ Opening email app..." : "Send Report →"}
          </button>
        </div>
      </div>

      {/* ── PRINTABLE REPORT BODY ─────────────────────────────────────────── */}
      <div id="report-body" className="space-y-6">

        {/* Profile */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-card p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 bg-gradient-to-br from-violet-500 to-sky-500 rounded-xl flex items-center justify-center text-white text-xl">👤</div>
            <div className="font-bold text-gray-900 text-lg">Profile</div>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {[
              { label: "Name",         value: String(summary?.name || "—") },
              { label: "Health Goal",  value: String(summary?.primary_goal || "—").replace(/_/g, " ") },
              { label: "BMI Category", value: String(summary?.bmi_category || "—") },
              { label: "Age",          value: `${summary?.age || "—"} yrs` },
              { label: "Activity",     value: String(summary?.activity_level || "—").replace(/_/g, " ") },
              { label: "Cuisine",      value: String(summary?.cuisine_preference || "—") },
            ].map((item) => (
              <div key={item.label} className="bg-gray-50 rounded-xl p-3">
                <div className="text-xs text-gray-400 font-semibold uppercase tracking-wide">{item.label}</div>
                <div className="font-bold text-gray-800 mt-0.5 capitalize">{item.value}</div>
              </div>
            ))}
          </div>
          {conditionLabels.length > 0 && (
            <div className="mt-4 p-3 bg-violet-50 border border-violet-100 rounded-xl">
              <div className="text-xs font-bold text-violet-700 uppercase tracking-wide mb-2">Health Conditions</div>
              <div className="flex flex-wrap gap-2">
                {conditionLabels.map((l) => (
                  <span key={l} className="text-sm px-3 py-1 bg-violet-100 text-violet-800 rounded-full font-medium">{l}</span>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Nutrition Targets */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-card p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 bg-orange-100 rounded-xl flex items-center justify-center text-xl">🔥</div>
            <div className="font-bold text-gray-900 text-lg">Daily Nutrition Targets</div>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { label: "Calories",  value: `${cal} kcal`,  color: "text-orange-600" },
              { label: "Protein",   value: `${protein}g`,  color: "text-violet-600" },
              { label: "Carbs",     value: `${carbs}g`,    color: "text-sky-600"    },
              { label: "Fat",       value: `${fat}g`,      color: "text-emerald-600"},
            ].map((m) => (
              <div key={m.label} className="text-center bg-gray-50 rounded-xl p-4">
                <div className={`text-2xl font-black ${m.color}`}>{m.value}</div>
                <div className="text-xs text-gray-500 mt-1">{m.label}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Today's Meal Plan */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-card p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 bg-emerald-100 rounded-xl flex items-center justify-center text-xl">🥗</div>
            <div className="font-bold text-gray-900 text-lg">Today&apos;s Meal Plan</div>
          </div>
          <div className="space-y-4">
            {meals.map((m: unknown) => {
              const slot = m as Record<string, unknown>;
              const slotName = String(slot.slot).replace(/_/g, " ");
              const items = ((slot.items as unknown[]) || []).map((i: unknown) => ((i as Record<string, unknown>)?.food as Record<string, unknown>)?.name as string || "").filter(Boolean);
              const slotCal = Math.round(Number(slot.slot_calories) || 0);
              const slotP   = Math.round(Number(slot.slot_protein_g) || 0);
              const icons: Record<string, string> = { breakfast: "🌅", mid_morning: "🍎", lunch: "☀️", evening_snack: "🌤", dinner: "🌙" };
              return (
                <div key={String(slot.slot)} className="flex gap-4 p-4 bg-gray-50 rounded-xl">
                  <div className="text-2xl flex-shrink-0">{icons[String(slot.slot)] || "🍽"}</div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="font-bold text-gray-900 capitalize">{slotName}</span>
                      <span className="text-xs text-gray-400">{slotCal} kcal · {slotP}g protein</span>
                    </div>
                    <div className="text-sm text-gray-600">{items.join(" · ")}</div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Progress Logs */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-card p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 bg-sky-100 rounded-xl flex items-center justify-center text-xl">📊</div>
            <div className="font-bold text-gray-900 text-lg">Recent Progress (last 7 days)</div>
          </div>
          {recentLogs.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-xs text-gray-400 uppercase tracking-wide bg-gray-50">
                    <th className="px-3 py-2 text-left">Date</th>
                    <th className="px-3 py-2 text-right">Weight</th>
                    <th className="px-3 py-2 text-right">BP</th>
                    <th className="px-3 py-2 text-right">Sugar F/PM</th>
                    <th className="px-3 py-2 text-right">Sleep</th>
                    <th className="px-3 py-2 text-right">Steps</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-50">
                  {recentLogs.map((log) => (
                    <tr key={log.log_date}>
                      <td className="px-3 py-2 font-medium text-gray-800">{log.log_date}</td>
                      <td className="px-3 py-2 text-right text-gray-600">{log.weight_kg ? `${log.weight_kg}kg` : "—"}</td>
                      <td className="px-3 py-2 text-right text-gray-600">{log.bp_systolic ? `${log.bp_systolic}/${log.bp_diastolic}` : "—"}</td>
                      <td className="px-3 py-2 text-right text-gray-600">{log.blood_sugar_fasting || "—"} / {log.blood_sugar_post_meal || "—"}</td>
                      <td className="px-3 py-2 text-right text-gray-600">{log.sleep_hours ? `${log.sleep_hours}h` : "—"}</td>
                      <td className="px-3 py-2 text-right text-gray-600">{log.steps_count?.toLocaleString() || "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="text-center py-6 text-gray-400 text-sm">
              No progress data yet — start logging in the Progress section.
            </div>
          )}
        </div>

        {/* Wellness Reminders */}
        <div className="bg-gradient-to-br from-slate-800 to-slate-900 text-white rounded-2xl p-6">
          <div className="font-bold text-lg mb-4">🌟 Your Daily Wellness Reminders</div>
          <div className="grid md:grid-cols-2 gap-3">
            {[
              { icon: "🚶", tip: "Walk 30 min daily — reduces heart disease risk by 35%" },
              { icon: "🏋️", tip: "Strength train 2–3×/week — lowers blood sugar & builds metabolism" },
              { icon: "🥗", tip: "Eat protein at every meal — keeps you full and protects muscle" },
              { icon: "💧", tip: "Drink water before meals — reduces hunger naturally" },
              { icon: "😴", tip: "7–8 hours sleep — regulates hunger hormones and insulin" },
              { icon: "🧘", tip: "10 min meditation daily — lowers cortisol and blood pressure" },
              { icon: "🥦", tip: "Half your plate = vegetables — fibre, vitamins, almost no calories" },
              { icon: "⏰", tip: "Consistent meal timings — prevents blood sugar swings" },
            ].map((r) => (
              <div key={r.tip} className="flex items-start gap-2 text-sm text-slate-200">
                <span className="flex-shrink-0">{r.icon}</span>
                <span>{r.tip}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Disclaimer */}
        <div className="text-xs text-gray-400 bg-gray-50 rounded-xl p-4 text-center">
          ⚕ This report is for personal wellness tracking only and is not a substitute for medical advice.
          Always consult your doctor or dietician before making changes to your diet, exercise or medications.
        </div>
      </div>

      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { background: white; }
        }
      `}</style>
    </div>
  );
}
